name: CI

on:
  push:
    branches: [ "master", "develop" ]

env:
  dotnet-version: 6.0.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Configuring .NET SDK ${{ env.dotnet-version }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.dotnet-version }}
        
    - name: Installing GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
        
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        configFilePath: gitversion.yml
