name: CI

on:
  push:
    branches: [ "master", "develop" ]

env:
  dotnet-version: 6.0.x
  project-name: RabbitWrapped

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Configure .NET SDK ${{ env.dotnet-version }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.dotnet-version }}
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
        
    - name: Generate version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        configFilePath: gitversion.yml
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.project-name }}
      
    - name: Build project
      run: dotnet build ${{ env.project-name }} -c Release --no-restore /p:Version=$GitVersion_SemVer
      
    - name: Create package
      run: dotnet pack ${{ env.project-name }} -c Release --no-build
      
    - name: Upload package
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
      
    - name: Add tag
      uses: rickstaa/action-create-tag@v1
      with:
        tag: 'v$GitVersion_SemVer'
